pipeline:
  name: Create Cluster and Deploy Mangler Club
  identifier: Create_Cluster_and_Deploy_Mangler_Club
  projectIdentifier: Hubot
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.suranc_Account_Level
        repoName: fugawi-mangler-club
        build: <+input>
  stages:
    - stage:
        name: Create Cluster
        identifier: Create_Cluster
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformDestroy
                  name: Destroy Existing Cluster
                  identifier: Destroy_Existing_Cluster
                  spec:
                    provisionerIdentifier: ibmcloud_cluster
                    configuration:
                      type: Inline
                      spec:
                        configFiles:
                          store:
                            spec:
                              connectorRef: account.suranc_Account_Level
                              repoName: ibmcloud-free-cluster-terraform
                              gitFetchType: Branch
                              branch: master
                              folderPath: .
                            type: Github
                        varFiles:
                          - varFile:
                              spec:
                                content: ibmcloud_api_key = "<+secrets.getValue("ibmCloudKey")>"
                              identifier: ibmcloud_api_key
                              type: Inline
                  timeout: 10m
              - step:
                  type: Wait
                  name: Wait 10 Minutes for Delete to Settle
                  identifier: Wait_10_Minutes_for_Delete_to_Settle
                  spec:
                    duration: 10m
              - step:
                  type: TerraformApply
                  name: Create Cluster
                  identifier: Create_Cluster
                  spec:
                    configuration:
                      type: Inline
                      spec:
                        configFiles:
                          store:
                            type: Github
                            spec:
                              gitFetchType: Branch
                              connectorRef: account.suranc_Account_Level
                              repoName: ibmcloud-free-cluster-terraform
                              branch: master
                              folderPath: .
                        varFiles:
                          - varFile:
                              spec:
                                content: ibmcloud_api_key = "<+secrets.getValue("ibmCloudKey")>"
                              identifier: ibmcloud_create_cluster_api_key
                              type: Inline
                    provisionerIdentifier: ibmcloud_cluster
                  timeout: 10m
              - step:
                  type: Wait
                  name: Wait 15 Minutes for Cluster Creation to Settle
                  identifier: Wait_15_Minutes_for_Cluster_Creation_to_Settle
                  spec:
                    duration: 15m
        tags: {}
        when:
          pipelineStatus: Success
          condition: "false"
    - stage:
        name: Update Cluster
        identifier: Update_Cluster
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Log in to Cluster and get kubeconfig
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: ghcr.io/suranc/ibmcloud-cli
                    shell: Sh
                    command: |
                      ibmcloud login --apikey "<+secrets.getValue("ibmCloudKey")>" -r us-south
                      ibmcloud ks cluster config -c harness-cluster --output yaml > kubeconfig.yaml
                      md5sum kubeconfig.yaml
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.sacluster
              namespace: chris-builds
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        when:
          pipelineStatus: Success
