pipeline:
  name: Create Cluster and Deploy Mangler Club
  identifier: Create_Cluster_and_Deploy_Mangler_Club
  projectIdentifier: Hubot
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.suranc_Account_Level
        repoName: fugawi-mangler-club
        build: <+input>
  stages:
    - stage:
        name: Create Cluster
        identifier: Create_Cluster
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Background
                  name: Background_1
                  identifier: Background_1
                  spec:
                    connectorRef: account.harnessImage
                    image: docker:dind
                    shell: Sh
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Sh
                    command: echo test
              - step:
                  type: Plugin
                  name: Plugin_1
                  identifier: Plugin_1
                  spec:
                    connectorRef: account.harnessImage
                    image: plugins/github-actions
                    settings:
                      uses: suranc/example-action@master
                      with: "{\"example-input\": \"testinputval\"}"
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.sacluster
              namespace: chris-builds
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          sharedPaths:
            - /var/run
