pipeline:
  name: Create Cluster and Deploy Mangler Club
  identifier: Create_Cluster_and_Deploy_Mangler_Club
  projectIdentifier: Hubot
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.suranc_Account_Level
        repoName: fugawi-mangler-club
        build: <+input>
  stages:
    - stage:
        name: Create Cluster
        identifier: Create_Cluster
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformApply
                  name: Create Cluster
                  identifier: Create_Cluster
                  spec:
                    configuration:
                      type: Inline
                      spec:
                        configFiles:
                          store:
                            type: Github
                            spec:
                              gitFetchType: Branch
                              connectorRef: account.suranc_Account_Level
                              repoName: ibmcloud-terraform-example
                              branch: master
                              folderPath: .
                    provisionerIdentifier: ibmcloud_cluster
                  timeout: 10m
        tags: {}
    - stage:
        name: Update Cluster
        identifier: Update_Cluster
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Sh
                    command: echo test
              - step:
                  type: Plugin
                  name: Plugin_1
                  identifier: Plugin_1
                  spec:
                    connectorRef: account.harnessImage
                    image: plugins/github-actions
                    privileged: true
                    settings:
                      uses: suranc/example-action@master
                      with: "{\"example-input\": \"testinputval\"}"
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.sacluster
              namespace: chris-builds
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
