---
apiVersion: v1
kind: Namespace
metadata:
  name: fugawi 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytrnd
  namespace: fugawi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ytrnd
  template:
    metadata:
      labels:
        app: ytrnd
    spec:
      containers:
      - name: ytrnd
        image: suranc/ytrnd:0.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ytrnd-service
  namespace: fugawi
  labels:
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: ytrnd
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ytrnd-ingress
  namespace: fugawi
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: ytrnd.mangler.cyou
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ytrnd-service
            port:
              number: 80
  - host: tsr.mangler.cyou
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ytrnd-service
            port:
              number: 80